[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
colored = "2.0.4"
motif-git = { path = "crates/motif-git" }
motif-one-drop = { path = "crates/motif-one-drop" }
motif-hash = { path = "crates/motif-hash" }
