[package]
name = "motif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
colored.workspace = true
motif-git.workspace = true
motif-one-drop.workspace = true
motif-hash.workspace = true
